#!/bin/bash

function nothing() {
  echo "usage:"
  echo "car               -- Simplified operation"
  echo "| ./car init      -- init basic folder"
  echo "| ./car help      -- help infomation"
  echo "| ./car camera    -- adjust car camera by computer"
  echo "| ./car start     -- control car by computer"
  echo "| ./car check     -- check if picture is empty"
  echo "| ./car train     -- train network"
  echo "| ./car auto      -- control car by network"
  echo "| ./car clean     -- clean useless image and model"
  echo "V"
}

function help() {
  nothing
  echo "         _____________________________ "
  echo "        |                             |"
  echo "        | q w                       p |"
  echo "        | a   d              h j k l  |"
  echo "        |                             |"
  echo "        |                             |"
  echo "        |            _____            |"
  echo "        |           |space|           |"
  echo "        |            -----            |"
  echo "        |_____________________________|"
  echo ""
  echo "    w:  car start, adjust direction to forward"
  echo "    a:  car start, adjust direction to left"
  echo "    d:  car start, adjust direction to right"
  echo "    h:  car camera, adjust camera left"
  echo "    j:  car camera, adjust camera down"
  echo "    k:  car camera, adjust camera up"
  echo "    l:  car camera, adjust camera right"
  echo "    p:  car auto, stop toy-car"
  echo "    q:  car start/auto, end program"
  echo "space:  car start/auto, forward then stop; stop then forward"
}

function init() {
  if [ ! -d "html/data/a" ]; then
    mkdir -p html/data/a
  fi
  if [ ! -d "html/data/d" ]; then
    mkdir -p html/data/d
  fi
  if [ ! -d "html/data/w" ]; then
    mkdir -p html/data/w
  fi
  if [ ! -d "network/model" ]; then
    mkdir -p network/model
  fi
}

function camera() {
  python3 ./control/CameraAdjust.py
}

function start() {
  echo "car start..."
  init
  python3 ./control/Car.py
}

function check() {
  python3 ./tools/check.py ./html/data/
}

function train() {
  echo "network train..."
  python3 ./network/Train.py
}

function auto() {
  echo "car drive..."
  python3 ./network/Car.py
}

function clean() {
  echo "remove data..."
  if [ ! -f "./html/data/" ]; then
    rm -rf ./html/data/*
  fi
  echo "remove model..."
  if [ ! -f "./network/model/" ]; then
    rm -rf ./network/model/*
  fi
  echo "remove __pycache__"
  if [ ! -f "./control/__pycache__" ]; then
    rm -rf ./control/__pycache__
  fi
  if [ ! -f "./network/__pycache__" ]; then
    rm -rf ./network/__pycache__
  fi
}

function main() {
  echo $cmd
  if [ -z $cmd ]; then
    nothing
    exit 1
  fi

  if [ $cmd == 'help' ]; then
    help
  elif [ $cmd == 'init' ]; then
    init
  elif [ $cmd == 'camera' ]; then
    camera
  elif [ $cmd == 'start' ]; then
    start
  elif [ $cmd == 'check' ]; then
    check
  elif [ $cmd == 'train' ]; then
    train
  elif [ $cmd == 'auto' ]; then
    auto
  elif [ $cmd == 'clean' ]; then
    clean
  else
    ./car
  fi
}

cmd=$1
main
